### ISSUE TITLE
Suggestion: link back to this repository from the site

### ISSUE THREAD

**Issue by ccoenen** [umgustavo/discord-timestamp-generator#1]
Looking for ["discord-timestamp-generator"](https://duckduckgo.com/?q=github+discord-timestamp-generator) yields quite a few projects. I think it would be a good idea to have a link on the website that points users at this repository.

**Comment by n0ky4** [comment]
Hey,

Thanks for the suggestion. I made a new commit with this feature.

Closing this issue now ;)
